apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
spec:
  destination:
    name: in-cluster
    namespace: default
  project: infrastructure
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 68.3.2
    chart: kube-prometheus-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true