apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  #namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: infrastructure
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 68.3.2
    chart: kube-prometheus-stack